let c = [
  { label: "A'aba", value: "A'aba" },
  { label: "Aazki", value: "Aazki" },
  { label: "Abbassiyeh", value: "Abbassiyeh" },
  { label: "Abboudiyeh", value: "Abboudiyeh" },
  { label: "Abdeh", value: "Abdeh" },
  { label: "Abdelli", value: "Abdelli" },
  { label: "Ablah", value: "Ablah" },
  { label: "Abra", value: "Abra" },
  { label: "Achach", value: "Achach" },
  { label: "Achkout", value: "Achkout" },
  { label: "Achrafieh", value: "Achrafieh" },
  { label: "Adchit", value: "Adchit" },
  { label: "Addoussiyeh", value: "Addoussiyeh" },
  { label: "Adloun", value: "Adloun" },
  { label: "Adma", value: "Adma" },
  { label: "Adra", value: "Adra" },
  { label: "Afka", value: "Afka" },
  { label: "Afsdik", value: "Afsdik" },
  { label: "Aghmid", value: "Aghmid" },
  { label: "Aidamoun", value: "Aidamoun" },
  { label: "Aiha", value: "Aiha" },
  { label: "Ain Aar", value: "Ain Aar" },
  { label: "Ain Akrine", value: "Ain Akrine" },
  { label: "Ain el-Delb", value: "Ain el-Delb" },
  { label: "Ain Alak", value: "Ain Alak" },
  { label: "Ain Ab", value: "Ain Ab" },
  { label: "Ain Anoub", value: "Ain Anoub" },
  { label: "Ain Arab", value: "Ain Arab" },
  { label: "Ain Ata", value: "Ain Ata" },
  { label: "Ain Ba'al", value: "Ain Ba'al" },
  { label: "Ain Baniyeh", value: "Ain Baniyeh" },
  { label: "Ain Bourday", value: "Ain Bourday" },
  { label: "Ain Boussouar", value: "Ain Boussouar" },
  { label: "Ain Dara", value: "Ain Dara" },
  { label: "Ain Ebel", value: "Ain Ebel" },
  { label: "Ain el-Ghoaybeh", value: "Ain el-Ghoaybeh" },
  { label: "Ain el-Kharroubeh", value: "Ain el-Kharroubeh" },
  { label: "Ain el-Remmaneh", value: "Ain el-Remmaneh" },
  { label: "Ain el-Rihani", value: "Ain el-Rihani" },
  { label: "Ain el-Safsaf", value: "Ain el-Safsaf" },
  { label: "Ain el-Tini", value: "Ain el-Tini" },
  { label: "Ain Enoub", value: "Ain Enoub" },
  { label: "Ain Harcha", value: "Ain Harcha" },
  { label: "Ain Jdideh", value: "Ain Jdideh" },
  { label: "Ain Joz", value: "Ain Joz" },
  { label: "Ain Kfarzabad", value: "Ain Kfarzabad" },
  { label: "Ain Ksour", value: "Ain Ksour" },
  { label: "Ain Mouaffaq", value: "Ain Mouaffaq" },
  { label: "Ain Mreisseh", value: "Ain Mreisseh" },
  { label: "Ain Qana", value: "Ain Qana" },
  { label: "Ain Saadeh", value: "Ain Saadeh" },
  { label: "Ain Saouda", value: "Ain Saouda" },
  { label: "Ain Tanta", value: "Ain Tanta" },
  { label: "Ain Tini", value: "Ain Tini" },
  { label: "Ain Toubine", value: "Ain Toubine" },
  { label: "Ain Toura", value: "Ain Toura" },
  { label: "Ain Toura", value: "Ain Toura" },
  { label: "Ain Tourine", value: "Ain Tourine" },
  { label: "Ain Trez", value: "Ain Trez" },
  { label: "Ain We Zein", value: "Ain We Zein" },
  { label: "Ain Yaacoub", value: "Ain Yaacoub" },
  { label: "Ain Zabad", value: "Ain Zabad" },
  { label: "Ain Zaite", value: "Ain Zaite" },
  { label: "Ain Zebdeh", value: "Ain Zebdeh" },
  { label: "Aita el-Fakhar", value: "Aita el-Fakhar" },
  { label: "Aita el-Zot", value: "Aita el-Zot" },
  { label: "Aitanit", value: "Aitanit" },
  { label: "Aïtat", value: "Aïtat" },
  { label: "Aitou", value: "Aitou" },
  { label: "Aitouli", value: "Aitouli" },
  { label: "Ajad Ebrine", value: "Ajad Ebrine" },
  { label: "Ajaltoun", value: "Ajaltoun" },
  { label: "Akaybeh", value: "Akaybeh" },
  { label: "Akbeh", value: "Akbeh" },
  { label: "Akidiyeh", value: "Akidiyeh" },
  { label: "Akkar el-Atika", value: "Akkar el-Atika" },
  { label: "Akoura", value: "Akoura" },
  { label: "Akroum", value: "Akroum" },
  { label: "Aktanit", value: "Aktanit" },
  { label: "Al Abdeh", value: "Al Abdeh" },
  { label: "Al Ain", value: "Al Ain" },
  { label: "Al Ali", value: "Al Ali" },
  { label: "Al Haddadine", value: "Al Haddadine" },
  { label: "Al Hadid", value: "Al Hadid" },
  { label: "Al Hid", value: "Al Hid" },
  { label: "Al Hiri", value: "Al Hiri" },
  { label: "Al Hmayra", value: "Al Hmayra" },
  { label: "Al Mahatra", value: "Al Mahatra" },
  { label: "Al Sahleh", value: "Al Sahleh" },
  { label: "Al Saksakieh", value: "Al Saksakieh" },
  { label: "Al Sharkiyeh", value: "Al Sharkiyeh" },
  { label: "Al Wardaniyeh", value: "Al Wardaniyeh" },
  { label: "Aley", value: "Aley" },
  { label: "Ali el-Nahri", value: "Ali el-Nahri" },
  { label: "Alma", value: "Alma" },
  { label: "Alma el-Chaab", value: "Alma el-Chaab" },
  { label: "Almat", value: "Almat" },
  { label: "Amaret Chalhoub", value: "Amaret Chalhoub" },
  { label: "Amatour", value: "Amatour" },
  { label: "Amchit", value: "Amchit" },
  { label: "Amioun", value: "Amioun" },
  { label: "Ammar Bikat", value: "Ammar Bikat" },
  { label: "Ammik", value: "Ammik" },
  { label: "Ammik", value: "Ammik" },
  { label: "An Nouri", value: "An Nouri" },
  { label: "Ana", value: "Ana" },
  { label: "Andket", value: "Andket" },
  { label: "Andoula", value: "Andoula" },
  { label: "Anfeh", value: "Anfeh" },
  { label: "Anjar", value: "Anjar" },
  { label: "Ankoun", value: "Ankoun" },
  { label: "Ankoune", value: "Ankoune" },
  { label: "Anout", value: "Anout" },
  { label: "Ansar", value: "Ansar" },
  { label: "Anssarieh", value: "Anssarieh" },
  { label: "Antelias", value: "Antelias" },
  { label: "Arab el-Jal", value: "Arab el-Jal" },
  { label: "Arab Salim", value: "Arab Salim" },
  { label: "Arabet Kozhaya", value: "Arabet Kozhaya" },
  { label: "Aramoun", value: "Aramoun" },
  { label: "Aramoun", value: "Aramoun" },
  { label: "Araya", value: "Araya" },
  { label: "Arbaniyeh", value: "Arbaniyeh" },
  { label: "Ardeh", value: "Ardeh" },
  { label: "Arida", value: "Arida" },
  { label: "Arjess", value: "Arjess" },
  { label: "Arkeh", value: "Arkeh" },
  { label: "Artez", value: "Artez" },
  { label: "Arzeh", value: "Arzeh" },
  { label: "Arzi", value: "Arzi" },
  { label: "Arzoune", value: "Arzoune" },
  { label: "Aslout", value: "Aslout" },
  { label: "Asnoun", value: "Asnoun" },
  { label: "Assaouneh", value: "Assaouneh" },
  { label: "Assoune", value: "Assoune" },
  { label: "Atchaneh", value: "Atchaneh" },
  { label: "Atrine", value: "Atrine" },
  { label: "Awkar", value: "Awkar" },
  { label: "Awra", value: "Awra" },
  { label: "Ayat", value: "Ayat" },
  { label: "Ayroune", value: "Ayroune" },
  { label: "Aytate", value: "Aytate" },
  { label: "Aytite", value: "Aytite" },
  { label: "Azzeh", value: "Azzeh" },
  { label: "Chaat", value: "Chaat" },
  { label: "Chabiyeh", value: "Chabiyeh" },
  { label: "Chacra", value: "Chacra" },
  { label: "Chadra", value: "Chadra" },
  { label: "Chaet", value: "Chaet" },
  { label: "Chahour", value: "Chahour" },
  { label: "Chakdouf", value: "Chakdouf" },
  { label: "Chamat", value: "Chamat" },
  { label: "Chamout", value: "Chamout" },
  { label: "Chane", value: "Chane" },
  { label: "Charbila", value: "Charbila" },
  { label: "Charbin", value: "Charbin" },
  { label: "Charoun", value: "Charoun" },
  { label: "Charqiyeh", value: "Charqiyeh" },
  { label: "Chartoun", value: "Chartoun" },
  { label: "Chatine", value: "Chatine" },
  { label: "Chatiyeh", value: "Chatiyeh" },
  { label: "Chawaghir", value: "Chawaghir" },
  { label: "Chawiya", value: "Chawiya" },
  { label: "Cheaibi", value: "Cheaibi" },
  { label: "Cheaytieh", value: "Cheaytieh" },
  { label: "Chebaniyeh", value: "Chebaniyeh" },
  { label: "Chehabiyeh", value: "Chehabiyeh" },
  { label: "Chehim", value: "Chehim" },
  { label: "Cheikh Mohamad", value: "Cheikh Mohamad" },
  { label: "Cheikh Taba", value: "Cheikh Taba" },
  { label: "Cheikh Znad", value: "Cheikh Znad" },
  { label: "Chekka", value: "Chekka" },
  { label: "Chekka", value: "Chekka" },
  { label: "Chemlan", value: "Chemlan" },
  { label: "Chibtine", value: "Chibtine" },
  { label: "Chikhlar", value: "Chikhlar" },
  { label: "Chiyah", value: "Chiyah" },
  { label: "Chlifa", value: "Chlifa" },
  { label: "Chmais", value: "Chmais" },
  { label: "Chmeis", value: "Chmeis" },
  { label: "Chmestar", value: "Chmestar" },
  { label: "Chnanïïr", value: "Chnanïïr" },
  { label: "Choualik", value: "Choualik" },
  { label: "Choueifat", value: "Choueifat" },
  { label: "Choueir", value: "Choueir" },
  { label: "Choukine", value: "Choukine" },
  { label: "Chourite", value: "Chourite" },
  { label: "Chrine", value: "Chrine" },
  { label: "Chtaheh", value: "Chtaheh" },
  { label: "Chtaura", value: "Chtaura" },
  { label: "Dabra", value: "Dabra" },
  { label: "Daghla", value: "Daghla" },
  { label: "Daher", value: "Daher" },
  { label: "Dahr Abou-Yaghi", value: "Dahr Abou-Yaghi" },
  { label: "Dahr el-Ahmar", value: "Dahr el-Ahmar" },
  { label: "Dahr el-Ain", value: "Dahr el-Ain" },
  { label: "Dahr el-Hassin", value: "Dahr el-Hassin" },
  { label: "Dahr el-Souan", value: "Dahr el-Souan" },
  { label: "Dahr Lisseineh", value: "Dahr Lisseineh" },
  { label: "Dail", value: "Dail" },
  { label: "Dakkouh", value: "Dakkouh" },
  { label: "Dalhoun", value: "Dalhoun" },
  { label: "Damour", value: "Damour" },
  { label: "Danbo", value: "Danbo" },
  { label: "Daousseh", value: "Daousseh" },
  { label: "Daphneh", value: "Daphneh" },
  { label: "Dar Aoun", value: "Dar Aoun" },
  { label: "Dar Aya", value: "Dar Aya" },
  { label: "Dar Aya", value: "Dar Aya" },
  { label: "Dar Baachtar", value: "Dar Baachtar" },
  { label: "Dar Chmezzine", value: "Dar Chmezzine" },
  { label: "Dar Wassiha", value: "Dar Wassiha" },
  { label: "Darbessim", value: "Darbessim" },
  { label: "Darine", value: "Darine" },
  { label: "Dawra", value: "Dawra" },
  { label: "Dbayeh", value: "Dbayeh" },
  { label: "Debabieh", value: "Debabieh" },
  { label: "Deb'al", value: "Deb'al" },
  { label: "Debbiyeh", value: "Debbiyeh" },
  { label: "Deddeh", value: "Deddeh" },
  { label: "Deir Achayer", value: "Deir Achayer" },
  { label: "Deir el-Zahrani", value: "Deir el-Zahrani" },
  { label: "Deir Ames", value: "Deir Ames" },
  { label: "Deir Ammar", value: "Deir Ammar" },
  { label: "Deir Antar", value: "Deir Antar" },
  { label: "Deir Baba", value: "Deir Baba" },
  { label: "Deir Bella", value: "Deir Bella" },
  { label: "Deir Chwah", value: "Deir Chwah" },
  { label: "Deir Dghaya", value: "Deir Dghaya" },
  { label: "Deir el-'Achaer", value: "Deir el-'Achaer" },
  { label: "Deir el-Ahmar", value: "Deir el-Ahmar" },
  { label: "Deir el-Kamar", value: "Deir el-Kamar" },
  { label: "Deir el-Moukhales", value: "Deir el-Moukhales" },
  { label: "Deir el-Ghazal", value: "Deir el-Ghazal" },
  { label: "Deir el-Harf", value: "Deir el-Harf" },
  { label: "Deir Janine", value: "Deir Janine" },
  { label: "Deir Kanoun", value: "Deir Kanoun" },
  { label: "Deir Kantar", value: "Deir Kantar" },
  { label: "Deir Kifa", value: "Deir Kifa" },
  { label: "Deir Koucheh", value: "Deir Koucheh" },
  { label: "Deir Mimas", value: "Deir Mimas" },
  { label: "Deir Nbouh", value: "Deir Nbouh" },
  { label: "Dekouaneh", value: "Dekouaneh" },
  { label: "Delhamiyeh", value: "Delhamiyeh" },
  { label: "Derb el-Simme", value: "Derb el-Simme" },
  { label: "Deria", value: "Deria" },
  { label: "Deychounieh", value: "Deychounieh" },
  { label: "Dfoun", value: "Dfoun" },
  { label: "Dibiil", value: "Dibiil" },
  { label: "Dlaybeh", value: "Dlaybeh" },
  { label: "Dlebta", value: "Dlebta" },
  { label: "Dmayt", value: "Dmayt" },
  { label: "Douar", value: "Douar" },
  { label: "Doubiyeh", value: "Doubiyeh" },
  { label: "Doueir", value: "Doueir" },
  { label: "Doueir Adouieh", value: "Doueir Adouieh" },
  { label: "Doueir el-Remmane", value: "Doueir el-Remmane" },
  { label: "Douma", value: "Douma" },
  { label: "Douma", value: "Douma" },
  { label: "Douriss", value: "Douriss" },
  { label: "Edbel", value: "Edbel" },
  { label: "Eddeh", value: "Eddeh" },
  { label: "Eddeh", value: "Eddeh" },
  { label: "Ehden", value: "Ehden" },
  { label: "Ehmej", value: "Ehmej" },
  { label: "Ein Zeitouneh", value: "Ein Zeitouneh" },
  { label: "Ejbeh", value: "Ejbeh" },
  { label: "el-Ain", value: "el-Ain" },
  { label: "Elhat", value: "Elhat" },
  { label: "el-Kaakour", value: "el-Kaakour" },
  { label: "el-Khalleh", value: "el-Khalleh" },
  { label: "el-Qalaa", value: "el-Qalaa" },
  { label: "el-Qarieh", value: "el-Qarieh" },
  { label: "Ersal", value: "Ersal" },
  { label: "Fakiha", value: "Fakiha" },
  { label: "Falaoui", value: "Falaoui" },
  { label: "Falougha", value: "Falougha" },
  { label: "Fanar", value: "Fanar" },
  { label: "Fatreh", value: "Fatreh" },
  { label: "Fayadieh", value: "Fayadieh" },
  { label: "Feghal", value: "Feghal" },
  { label: "Ferzol", value: "Ferzol" },
  { label: "Fesdick", value: "Fesdick" },
  { label: "Feytroun", value: "Feytroun" },
  { label: "Fidar", value: "Fidar" },
  { label: "Fieh", value: "Fieh" },
  { label: "Fissane", value: "Fissane" },
  { label: "Fneidek", value: "Fneidek" },
  { label: "Fouara", value: "Fouara" },
  { label: "Freidess", value: "Freidess" },
  { label: "Freidis", value: "Freidis" },
  { label: "Freikeh", value: "Freikeh" },
  { label: "Froun", value: "Froun" },
  { label: "Ftahat", value: "Ftahat" },
  { label: "Furn el-Chebbak", value: "Furn el-Chebbak" },
  { label: "Garabache", value: "Garabache" },
  { label: "Geba'a", value: "Geba'a" },
  { label: "Gebrayel", value: "Gebrayel" },
  { label: "Ghafra", value: "Ghafra" },
  { label: "Ghalboun", value: "Ghalboun" },
  { label: "Ghandouriyeh", value: "Ghandouriyeh" },
  { label: "Gharayeb", value: "Gharayeb" },
  { label: "Gharifeh", value: "Gharifeh" },
  { label: "Ghassaniyeh", value: "Ghassaniyeh" },
  { label: "Ghassaniyeh", value: "Ghassaniyeh" },
  { label: "Ghazir", value: "Ghazir" },
  { label: "Ghaziyeh", value: "Ghaziyeh" },
  { label: "Ghazzeh", value: "Ghazzeh" },
  { label: "Ghebaleh", value: "Ghebaleh" },
  { label: "Ghineh", value: "Ghineh" },
  { label: "Ghobeïry", value: "Ghobeïry" },
  { label: "Ghosta", value: "Ghosta" },
  { label: "Ghouma", value: "Ghouma" },
  { label: "Ghowaya", value: "Ghowaya" },
  { label: "Ghreibeh", value: "Ghreibeh" },
  { label: "Ghzaileh", value: "Ghzaileh" },
  { label: "Habbouche", value: "Habbouche" },
  { label: "Habchit", value: "Habchit" },
  { label: "Habil", value: "Habil" },
  { label: "Habrmoun", value: "Habrmoun" },
  { label: "Hadchit", value: "Hadchit" },
  { label: "Haddatha", value: "Haddatha" },
  { label: "Hadeth", value: "Hadeth" },
  { label: "Hadeth Baalbeck", value: "Hadeth Baalbeck" },
  { label: "Hadeth el-Joubbeh", value: "Hadeth el-Joubbeh" },
  { label: "Hadtoune", value: "Hadtoune" },
  { label: "Hageh", value: "Hageh" },
  { label: "Haissa", value: "Haissa" },
  { label: "Haizouk", value: "Haizouk" },
  { label: "HajjehJbeili", value: "HajjehJbeili" },
  { label: "Hakl el-Azimi", value: "Hakl el-Azimi" },
  { label: "Hakour", value: "Hakour" },
  { label: "Hakr Cheikh Taba", value: "Hakr Cheikh Taba" },
  { label: "Hakr Dahiri", value: "Hakr Dahiri" },
  { label: "Halate", value: "Halate" },
  { label: "Halba", value: "Halba" },
  { label: "Halloussiyeh", value: "Halloussiyeh" },
  { label: "Hamat", value: "Hamat" },
  { label: "Hamat", value: "Hamat" },
  { label: "Hame", value: "Hame" },
  { label: "Hammana", value: "Hammana" },
  { label: "Hamra", value: "Hamra" },
  { label: "Haniyeh", value: "Haniyeh" },
  { label: "Harbouna", value: "Harbouna" },
  { label: "Hardine", value: "Hardine" },
  { label: "Haret el-Botm", value: "Haret el-Botm" },
  { label: "Haret el-Fouar", value: "Haret el-Fouar" },
  { label: "Haret el-Khassa", value: "Haret el-Khassa" },
  { label: "Haret Hamzeh", value: "Haret Hamzeh" },
  { label: "Haret Hreik", value: "Haret Hreik" },
  { label: "Haret Maasser", value: "Haret Maasser" },
  { label: "Haret Saida", value: "Haret Saida" },
  { label: "Haret Saida", value: "Haret Saida" },
  { label: "Haret Sakhr", value: "Haret Sakhr" },
  { label: "Harf Ardeh", value: "Harf Ardeh" },
  { label: "Harf Miziara", value: "Harf Miziara" },
  { label: "Harf Siyad", value: "Harf Siyad" },
  { label: "Harika", value: "Harika" },
  { label: "Haris", value: "Haris" },
  { label: "Harissa", value: "Harissa" },
  { label: "Harouf", value: "Harouf" },
  { label: "Hasbaya", value: "Hasbaya" },
  { label: "Hasroun", value: "Hasroun" },
  { label: "Hasrout", value: "Hasrout" },
  { label: "Hawche", value: "Hawche" },
  { label: "Hay el-Sellom", value: "Hay el-Sellom" },
  { label: "Hay el-Fikati", value: "Hay el-Fikati" },
  { label: "Haylan", value: "Haylan" },
  { label: "Haysseh", value: "Haysseh" },
  { label: "Hazerta", value: "Hazerta" },
  { label: "Hazin", value: "Hazin" },
  { label: "Hazmieh", value: "Hazmieh" },
  { label: "Hbous", value: "Hbous" },
  { label: "Hed", value: "Hed" },
  { label: "Heloueh", value: "Heloueh" },
  { label: "Helta", value: "Helta" },
  { label: "Herhraya", value: "Herhraya" },
  { label: "Hermel", value: "Hermel" },
  { label: "Himlaya", value: "Himlaya" },
  { label: "Hitla", value: "Hitla" },
  { label: "Hjoula", value: "Hjoula" },
  { label: "Hlaliyeh", value: "Hlaliyeh" },
  { label: "Hlaliyeh", value: "Hlaliyeh" },
  { label: "Hmaiss", value: "Hmaiss" },
  { label: "Hmayreh", value: "Hmayreh" },
  { label: "Hmayreh", value: "Hmayreh" },
  { label: "Hmayreh", value: "Hmayreh" },
  { label: "Hneider", value: "Hneider" },
  { label: "Hoch el-Harimeh", value: "Hoch el-Harimeh" },
  { label: "Hoch el-Oumara", value: "Hoch el-Oumara" },
  { label: "Hoch Ghanam", value: "Hoch Ghanam" },
  { label: "Hoch Hala", value: "Hoch Hala" },
  { label: "Hoch Nabi", value: "Hoch Nabi" },
  { label: "Hoch Rafika", value: "Hoch Rafika" },
  { label: "Hoch Sayed", value: "Hoch Sayed" },
  { label: "Hoch Sneid", value: "Hoch Sneid" },
  { label: "Hoch Tal Safiyeh", value: "Hoch Tal Safiyeh" },
  { label: "Hoch Zahab", value: "Hoch Zahab" },
  { label: "Hoch Zarahneh", value: "Hoch Zarahneh" },
  { label: "Hocheb", value: "Hocheb" },
  { label: "Hor Tehla", value: "Hor Tehla" },
  { label: "Horch Hala", value: "Horch Hala" },
  { label: "Hosniyeh", value: "Hosniyeh" },
  { label: "Houmal", value: "Houmal" },
  { label: "Houmine", value: "Houmine" },
  { label: "Houwara", value: "Houwara" },
  { label: "Howeiche", value: "Howeiche" },
  { label: "Hrajel", value: "Hrajel" },
  { label: "Hrar", value: "Hrar" },
  { label: "Hrebta", value: "Hrebta" },
  { label: "Hsanieh", value: "Hsanieh" },
  { label: "Hsein", value: "Hsein" },
  { label: "Hsoun", value: "Hsoun" },
  { label: "Ia'al", value: "Ia'al" },
  { label: "Ia'at", value: "Ia'at" },
  { label: "Ibdine", value: "Ibdine" },
  { label: "Ibrine", value: "Ibrine" },
  { label: "Ighmid", value: "Ighmid" },
  { label: "Izal", value: "Izal" },
  { label: "Jaba'a", value: "Jaba'a" },
  { label: "Jadayel", value: "Jadayel" },
  { label: "Jahlieh", value: "Jahlieh" },
  { label: "Jaj", value: "Jaj" },
  { label: "Jal el-Dib", value: "Jal el-Dib" },
  { label: "Jalala", value: "Jalala" },
  { label: "Jalisseh", value: "Jalisseh" },
  { label: "Janneh", value: "Janneh" },
  { label: "Jarjouh", value: "Jarjouh" },
  { label: "Jawar Hachich", value: "Jawar Hachich" },
  { label: "Jbaa", value: "Jbaa" },
  { label: "Jbaa", value: "Jbaa" },
  { label: "Jbal Boutoum", value: "Jbal Boutoum" },
  { label: "Jbaniyeh", value: "Jbaniyeh" },
  { label: "Jbeil", value: "Jbeil" },
  { label: "Jboula", value: "Jboula" },
  { label: "Jdabra", value: "Jdabra" },
  { label: "Jdeideh", value: "Jdeideh" },
  { label: "Jdeideh", value: "Jdeideh" },
  { label: "JdeidehJoumeh", value: "JdeidehJoumeh" },
  { label: "JdeidehKatih", value: "JdeidehKatih" },
  { label: "Jdeidet el-Chouf", value: "Jdeidet el-Chouf" },
  { label: "Jdeidet Ghazir", value: "Jdeidet Ghazir" },
  { label: "Jdeidet Marjeyoun", value: "Jdeidet Marjeyoun" },
  { label: "Jdita", value: "Jdita" },
  { label: "Jeb Chite", value: "Jeb Chite" },
  { label: "Jeb Jenine", value: "Jeb Jenine" },
  { label: "Jeb La", value: "Jeb La" },
  { label: "Jeita", value: "Jeita" },
  { label: "Jenejleya", value: "Jenejleya" },
  { label: "Jensnaya", value: "Jensnaya" },
  { label: "Jenta", value: "Jenta" },
  { label: "Jernaya", value: "Jernaya" },
  { label: "Jidra", value: "Jidra" },
  { label: "Jisrain", value: "Jisrain" },
  { label: "Jiyeh", value: "Jiyeh" },
  { label: "Jmaijmeh", value: "Jmaijmeh" },
  { label: "Jouar", value: "Jouar" },
  { label: "Jouar el-Haouz", value: "Jouar el-Haouz" },
  { label: "Joun", value: "Joun" },
  { label: "Jounieh", value: "Jounieh" },
  { label: "Jouret Bedrane", value: "Jouret Bedrane" },
  { label: "Jouret el-Ballout", value: "Jouret el-Ballout" },
  { label: "Jouret el-Tourmos", value: "Jouret el-Tourmos" },
  { label: "Jouwaya", value: "Jouwaya" },
  { label: "Jrabta", value: "Jrabta" },
  { label: "Jrane", value: "Jrane" },
  { label: "Ka'a", value: "Ka'a" },
  { label: "Ka'a el-Rim", value: "Ka'a el-Rim" },
  { label: "Ka'a kayet Snoubar", value: "Ka'a kayet Snoubar" },
  { label: "Ka'a Kour", value: "Ka'a Kour" },
  { label: "Kab Elias", value: "Kab Elias" },
  { label: "Kab Ousseh", value: "Kab Ousseh" },
  { label: "Kab Rikha", value: "Kab Rikha" },
  { label: "Kachlak", value: "Kachlak" },
  { label: "Kaddam", value: "Kaddam" },
  { label: "Kadriyeh", value: "Kadriyeh" },
  { label: "Kafra", value: "Kafra" },
  { label: "Kaftoun", value: "Kaftoun" },
  { label: "Kahaleh", value: "Kahaleh" },
  { label: "Kahf el-Malloul", value: "Kahf el-Malloul" },
  { label: "Kahlounieh", value: "Kahlounieh" },
  { label: "Kal Sabeh", value: "Kal Sabeh" },
  { label: "Kala'a", value: "Kala'a" },
  { label: "Kala'a", value: "Kala'a" },
  { label: "Kalamoun", value: "Kalamoun" },
  { label: "Kaled Sabeh", value: "Kaled Sabeh" },
  { label: "Kalhat", value: "Kalhat" },
  { label: "Kalya", value: "Kalya" },
  { label: "Kamed el-Loz", value: "Kamed el-Loz" },
  { label: "Kamel", value: "Kamel" },
  { label: "Kammamine", value: "Kammamine" },
  { label: "Kanabat", value: "Kanabat" },
  { label: "Kannarit", value: "Kannarit" },
  { label: "Kantra", value: "Kantra" },
  { label: "Karak", value: "Karak" },
  { label: "Karaoun", value: "Karaoun" },
  { label: "Karha", value: "Karha" },
  { label: "Karha", value: "Karha" },
  { label: "Kariyeh", value: "Kariyeh" },
  { label: "Karkha", value: "Karkha" },
  { label: "Karm Asfour", value: "Karm Asfour" },
  { label: "Karm el-Mehr", value: "Karm el-Mehr" },
  { label: "Karm Saddeh", value: "Karm Saddeh" },
  { label: "Karsita", value: "Karsita" },
  { label: "Karsouna", value: "Karsouna" },
  { label: "Kartaba", value: "Kartaba" },
  { label: "Kasr-Fissane", value: "Kasr-Fissane" },
  { label: "Kasser", value: "Kasser" },
  { label: "Kasser Naba", value: "Kasser Naba" },
  { label: "Katelbeh", value: "Katelbeh" },
  { label: "Kattara", value: "Kattara" },
  { label: "Kattine", value: "Kattine" },
  { label: "Kawkaba", value: "Kawkaba" },
  { label: "Kawssariet Sayad", value: "Kawssariet Sayad" },
  { label: "Kboula", value: "Kboula" },
  { label: "Kboula", value: "Kboula" },
  { label: "Kefraya", value: "Kefraya" },
  { label: "Kefraya", value: "Kefraya" },
  { label: "Kefraya", value: "Kefraya" },
  { label: "Keftine", value: "Keftine" },
  { label: "Kesya", value: "Kesya" },
  { label: "Ketermaya", value: "Ketermaya" },
  { label: "Keyfoun", value: "Keyfoun" },
  { label: "Kfa Rabida", value: "Kfa Rabida" },
  { label: "Kfar Aamey", value: "Kfar Aamey" },
  { label: "Kfar Abida", value: "Kfar Abida" },
  { label: "Kfar Akab", value: "Kfar Akab" },
  { label: "Kfar Akka", value: "Kfar Akka" },
  { label: "Kfar Amya", value: "Kfar Amya" },
  { label: "Kfar Aya", value: "Kfar Aya" },
  { label: "Kfar Bachit", value: "Kfar Bachit" },
  { label: "Kfar Bibnine", value: "Kfar Bibnine" },
  { label: "Kfar Bit", value: "Kfar Bit" },
  { label: "Kfar Chakhna", value: "Kfar Chakhna" },
  { label: "Kfar Chelal", value: "Kfar Chelal" },
  { label: "Kfar Chellam", value: "Kfar Chellam" },
  { label: "Kfar Chellane", value: "Kfar Chellane" },
  { label: "Kfar Chima", value: "Kfar Chima" },
  { label: "Kfar Chliman", value: "Kfar Chliman" },
  { label: "Kfar Dabach", value: "Kfar Dabach" },
  { label: "Kfar Dan", value: "Kfar Dan" },
  { label: "Kfar Diche", value: "Kfar Diche" },
  { label: "Kfar Dlakous", value: "Kfar Dlakous" },
  { label: "Kfar Dnisse", value: "Kfar Dnisse" },
  { label: "Kfar Doubine", value: "Kfar Doubine" },
  { label: "Kfar Fakoud", value: "Kfar Fakoud" },
  { label: "Kfar Fila", value: "Kfar Fila" },
  { label: "Kfar Fou", value: "Kfar Fou" },
  { label: "Kfar Habou", value: "Kfar Habou" },
  { label: "Kfar Halda", value: "Kfar Halda" },
  { label: "Kfar Harra", value: "Kfar Harra" },
  { label: "Kfar Hata", value: "Kfar Hata" },
  { label: "Kfar Hatna", value: "Kfar Hatna" },
  { label: "Kfar Hatta", value: "Kfar Hatta" },
  { label: "Kfar Hatta", value: "Kfar Hatta" },
  { label: "Kfar Hay", value: "Kfar Hay" },
  { label: "Kfar Hazir", value: "Kfar Hazir" },
  { label: "Kfar Helda", value: "Kfar Helda" },
  { label: "Kfar Hitti", value: "Kfar Hitti" },
  { label: "Kfar Houra", value: "Kfar Houra" },
  { label: "Kfar Jarra", value: "Kfar Jarra" },
  { label: "Kfar Kahel", value: "Kfar Kahel" },
  { label: "Kfar Katra", value: "Kfar Katra" },
  { label: "Kfar Keddeh", value: "Kfar Keddeh" },
  { label: "Kfar Kouk", value: "Kfar Kouk" },
  { label: "Kfar Mashoun", value: "Kfar Mashoun" },
  { label: "Kfar Mechki", value: "Kfar Mechki" },
  { label: "Kfar Melki", value: "Kfar Melki" },
  { label: "Kfar Melki", value: "Kfar Melki" },
  { label: "Kfar Melki", value: "Kfar Melki" },
  { label: "Kfar Nabrakh", value: "Kfar Nabrakh" },
  { label: "Kfar Nis", value: "Kfar Nis" },
  { label: "Kfar Noun", value: "Kfar Noun" },
  { label: "Kfar Remmane", value: "Kfar Remmane" },
  { label: "Kfar Saroun", value: "Kfar Saroun" },
  { label: "Kfar Seghab", value: "Kfar Seghab" },
  { label: "Kfar Selouan", value: "Kfar Selouan" },
  { label: "Kfar Selouane", value: "Kfar Selouane" },
  { label: "Kfar Sir", value: "Kfar Sir" },
  { label: "Kfar Tebnit", value: "Kfar Tebnit" },
  { label: "Kfar Tey", value: "Kfar Tey" },
  { label: "Kfar Toun", value: "Kfar Toun" },
  { label: "Kfar Yachit", value: "Kfar Yachit" },
  { label: "Kfar Yassine", value: "Kfar Yassine" },
  { label: "Kfar Zabad", value: "Kfar Zabad" },
  { label: "Kfar Zebian", value: "Kfar Zebian" },
  { label: "Kfar Zina", value: "Kfar Zina" },
  { label: "Kfeir", value: "Kfeir" },
  { label: "Kfifane", value: "Kfifane" },
  { label: "Kfoun", value: "Kfoun" },
  { label: "Kfour", value: "Kfour" },
  { label: "Kfour", value: "Kfour" },
  { label: "Kfour el-Arabi", value: "Kfour el-Arabi" },
  { label: "Khalouate", value: "Khalouate" },
  { label: "Kharayeb", value: "Kharayeb" },
  { label: "Kharnoub", value: "Kharnoub" },
  { label: "Khartoum", value: "Khartoum" },
  { label: "Khazize", value: "Khazize" },
  { label: "Kherbet Char", value: "Kherbet Char" },
  { label: "Kherbet Kanafar", value: "Kherbet Kanafar" },
  { label: "Kherbet Rouha", value: "Kherbet Rouha" },
  { label: "Khodr", value: "Khodr" },
  { label: "Khodr Bey", value: "Khodr Bey" },
  { label: "Khonchara", value: "Khonchara" },
  { label: "Khorbet Daoud", value: "Khorbet Daoud" },
  { label: "Khorbet Jrad", value: "Khorbet Jrad" },
  { label: "Khorbet Jundi", value: "Khorbet Jundi" },
  { label: "Khraybeh", value: "Khraybeh" },
  { label: "Khrayeb", value: "Khrayeb" },
  { label: "Khreybeh", value: "Khreybeh" },
  { label: "Khreybeh", value: "Khreybeh" },
  { label: "Kiniya", value: "Kiniya" },
  { label: "Klaouiyeh", value: "Klaouiyeh" },
  { label: "Klayaat", value: "Klayaat" },
  { label: "Klayleh", value: "Klayleh" },
  { label: "Kleiat", value: "Kleiat" },
  { label: "Kloud Bakieh", value: "Kloud Bakieh" },
  { label: "Knafez", value: "Knafez" },
  { label: "Knaytra", value: "Knaytra" },
  { label: "Kneisseh", value: "Kneisseh" },
  { label: "Kneisseh", value: "Kneisseh" },
  { label: "Kneisseh", value: "Kneisseh" },
  { label: "Kobayat", value: "Kobayat" },
  { label: "Kobbeh", value: "Kobbeh" },
  { label: "Kobbeh", value: "Kobbeh" },
  { label: "Kobbet Chamra", value: "Kobbet Chamra" },
  { label: "Koneitra", value: "Koneitra" },
  { label: "Korhaya", value: "Korhaya" },
  { label: "Korkef", value: "Korkef" },
  { label: "Kornayel", value: "Kornayel" },
  { label: "Korneh", value: "Korneh" },
  { label: "Kornet Chehwane", value: "Kornet Chehwane" },
  { label: "Kortada", value: "Kortada" },
  { label: "Kossaibeh", value: "Kossaibeh" },
  { label: "Kossaibi", value: "Kossaibi" },
  { label: "Koubba", value: "Koubba" },
  { label: "Koubbayeh", value: "Koubbayeh" },
  { label: "Koucha", value: "Koucha" },
  { label: "Kour", value: "Kour" },
  { label: "Kousba", value: "Kousba" },
  { label: "Koussaya", value: "Koussaya" },
  { label: "Kouwakh", value: "Kouwakh" },
  { label: "Krayat", value: "Krayat" },
  { label: "Krayyeh", value: "Krayyeh" },
  { label: "Krin", value: "Krin" },
  { label: "Kroum Arab", value: "Kroum Arab" },
  { label: "Ksaybeh", value: "Ksaybeh" },
  { label: "Kwachra", value: "Kwachra" },
  { label: "Laboueh", value: "Laboueh" },
  { label: "Lala", value: "Lala" },
  { label: "Lassa", value: "Lassa" },
  { label: "Lebaa", value: "Lebaa" },
  { label: "Lebbaya", value: "Lebbaya" },
  { label: "Leilaky", value: "Leilaky" },
  { label: "Limar", value: "Limar" },
  { label: "Loubiyeh", value: "Loubiyeh" },
  { label: "Loueizeh", value: "Loueizeh" },
  { label: "Maalaka", value: "Maalaka" },
  { label: "Maamariyeh", value: "Maamariyeh" },
  { label: "Maamiriyeh", value: "Maamiriyeh" },
  { label: "Maaraboun", value: "Maaraboun" },
  { label: "Maarakeh", value: "Maarakeh" },
  { label: "Maaroub", value: "Maaroub" },
  { label: "Maarouf", value: "Maarouf" },
  { label: "Maasriti", value: "Maasriti" },
  { label: "Maasser", value: "Maasser" },
  { label: "Maasser Beit Eddine", value: "Maasser Beit Eddine" },
  { label: "Machta Hammoud", value: "Machta Hammoud" },
  { label: "Machta Hassan", value: "Machta Hassan" },
  { label: "Machghara", value: "Machghara" },
  { label: "Maghdoucheh", value: "Maghdoucheh" },
  { label: "Maghroubella", value: "Maghroubella" },
  { label: "Mahrouni", value: "Mahrouni" },
  { label: "Majd Ala", value: "Majd Ala" },
  { label: "Majd Aloun", value: "Majd Aloun" },
  { label: "Majd El", value: "Majd El" },
  { label: "Majd El", value: "Majd El" },
  { label: "Majd El", value: "Majd El" },
  { label: "Majd el-Anjar", value: "Majd el-Anjar" },
  { label: "Majd el-Baana", value: "Majd el-Baana" },
  { label: "Majd el-Balhis", value: "Majd el-Balhis" },
  { label: "Majd el-Behna", value: "Majd el-Behna" },
  { label: "Majd el-Meouch", value: "Majd el-Meouch" },
  { label: "Majd el-Sel", value: "Majd el-Sel" },
  { label: "Majd el-Tarchich", value: "Majd el-Tarchich" },
  { label: "Majd el-Youne", value: "Majd el-Youne" },
  { label: "Majd el-Youne", value: "Majd el-Youne" },
  { label: "Majd el-Zoun", value: "Majd el-Zoun" },
  { label: "Majd Laya", value: "Majd Laya" },
  { label: "Majd Laya", value: "Majd Laya" },
  { label: "Majzoub", value: "Majzoub" },
  { label: "Makneh", value: "Makneh" },
  { label: "Makni", value: "Makni" },
  { label: "Maksi", value: "Maksi" },
  { label: "Malekyeh", value: "Malekyeh" },
  { label: "Manara", value: "Manara" },
  { label: "Mansoura", value: "Mansoura" },
  { label: "Mansouri", value: "Mansouri" },
  { label: "Mansourieh", value: "Mansourieh" },
  { label: "Mar Antonios", value: "Mar Antonios" },
  { label: "Mar Mema", value: "Mar Mema" },
  { label: "Mar Mikhael", value: "Mar Mikhael" },
  { label: "Mar Moussa", value: "Mar Moussa" },
  { label: "Mar Roukoz", value: "Mar Roukoz" },
  { label: "Mar Sarkis", value: "Mar Sarkis" },
  { label: "Mar Touma", value: "Mar Touma" },
  { label: "Marj", value: "Marj" },
  { label: "Marj", value: "Marj" },
  { label: "Marj Barja", value: "Marj Barja" },
  { label: "Marj el-Zouhour", value: "Marj el-Zouhour" },
  { label: "Marjaba", value: "Marjaba" },
  { label: "Markabta", value: "Markabta" },
  { label: "Marsati", value: "Marsati" },
  { label: "Mart Moura", value: "Mart Moura" },
  { label: "Marwaniyeh", value: "Marwaniyeh" },
  { label: "Marwaniyeh", value: "Marwaniyeh" },
  { label: "Maska", value: "Maska" },
  { label: "Masnah Zahra", value: "Masnah Zahra" },
  { label: "Massa", value: "Massa" },
  { label: "Massoudieh", value: "Massoudieh" },
  { label: "Mayassa", value: "Mayassa" },
  { label: "Mayfaidoun", value: "Mayfaidoun" },
  { label: "Mayfouk", value: "Mayfouk" },
  { label: "Mayrouba", value: "Mayrouba" },
  { label: "M'aysra", value: "M'aysra" },
  { label: "Mazboud", value: "Mazboud" },
  { label: "Mazraa", value: "Mazraa" },
  { label: "Mazraat Abou Slaybi", value: "Mazraat Abou Slaybi" },
  { label: "Mazraat el-Soueidan", value: "Mazraat el-Soueidan" },
  { label: "Mazraat Baldeh", value: "Mazraat Baldeh" },
  { label: "Mazraat Baldeh", value: "Mazraat Baldeh" },
  { label: "Mazraat Beit Matar", value: "Mazraat Beit Matar" },
  { label: "Mazraat Beit Slaybi", value: "Mazraat Beit Slaybi" },
  { label: "Mazraat Beit Tacham", value: "Mazraat Beit Tacham" },
  { label: "Mazraat Dalil", value: "Mazraat Dalil" },
  { label: "Mazra'at el-Syad", value: "Mazra'at el-Syad" },
  { label: "Mazraat el-Fraydiss", value: "Mazraat el-Fraydiss" },
  { label: "Mazraat el-Nahr", value: "Mazraat el-Nahr" },
  { label: "Mazraat Fakih", value: "Mazraat Fakih" },
  { label: "Mazraat Houka", value: "Mazraat Houka" },
  { label: "Mazraat Hreikess", value: "Mazraat Hreikess" },
  { label: "Mazraat Kfardebiane", value: "Mazraat Kfardebiane" },
  { label: "Mazraat Mechref", value: "Mazraat Mechref" },
  { label: "Mazraat Saged", value: "Mazraat Saged" },
  { label: "Mazraat Sayed", value: "Mazraat Sayed" },
  { label: "Mazraat Soueidan", value: "Mazraat Soueidan" },
  { label: "Mazraat Touffah", value: "Mazraat Touffah" },
  { label: "Mazraat Tout", value: "Mazraat Tout" },
  { label: "Mazraat Yachouh", value: "Mazraat Yachouh" },
  { label: "Mazraet Artousa", value: "Mazraet Artousa" },
  { label: "Mazraet el-Dahr", value: "Mazraet el-Dahr" },
  { label: "Mchan", value: "Mchan" },
  { label: "Mchikha", value: "Mchikha" },
  { label: "Mdawkha", value: "Mdawkha" },
  { label: "Mecherfeh", value: "Mecherfeh" },
  { label: "Mechha", value: "Mechha" },
  { label: "Mechmech", value: "Mechmech" },
  { label: "Mechmech", value: "Mechmech" },
  { label: "Mechref", value: "Mechref" },
  { label: "Medawar", value: "Medawar" },
  { label: "Mehmarche", value: "Mehmarche" },
  { label: "Mekhtlef", value: "Mekhtlef" },
  { label: "Mekrak", value: "Mekrak" },
  { label: "Memneh", value: "Memneh" },
  { label: "Mersty", value: "Mersty" },
  { label: "Metrit", value: "Metrit" },
  { label: "Mezher", value: "Mezher" },
  { label: "Meziara", value: "Meziara" },
  { label: "Mghayri", value: "Mghayri" },
  { label: "Mharabiyeh", value: "Mharabiyeh" },
  { label: "Mimes", value: "Mimes" },
  { label: "Mina", value: "Mina" },
  { label: "Minet el-Hosn", value: "Minet el-Hosn" },
  { label: "Minieh", value: "Minieh" },
  { label: "Minyara", value: "Minyara" },
  { label: "Miryata", value: "Miryata" },
  { label: "MiyehWe Miyeh", value: "MiyehWe Miyeh" },
  { label: "Miye We Miyeh", value: "Miye We Miyeh" },
  { label: "Mjadel", value: "Mjadel" },
  { label: "Mjeidel", value: "Mjeidel" },
  { label: "Mkaibleh", value: "Mkaibleh" },
  { label: "Mkaiteh", value: "Mkaiteh" },
  { label: "Mkalles", value: "Mkalles" },
  { label: "Moheidse", value: "Moheidse" },
  { label: "Moheidseh", value: "Moheidseh" },
  { label: "Moughaïrieh", value: "Moughaïrieh" },
  { label: "Mouhtakara", value: "Mouhtakara" },
  { label: "Mounjez", value: "Mounjez" },
  { label: "Mounsa", value: "Mounsa" },
  { label: "Mounsef", value: "Mounsef" },
  { label: "Mousseitbeh", value: "Mousseitbeh" },
  { label: "Mrah As-Sraje", value: "Mrah As-Sraje" },
  { label: "Mrah Az-Zeyat", value: "Mrah Az-Zeyat" },
  { label: "Mrah Chdid", value: "Mrah Chdid" },
  { label: "Mrah el-Ain", value: "Mrah el-Ain" },
  { label: "Mrah el-Hajj", value: "Mrah el-Hajj" },
  { label: "Mrah el-Hibas", value: "Mrah el-Hibas" },
  { label: "Mrah el-Khokh", value: "Mrah el-Khokh" },
  { label: "Mrah Sfaira", value: "Mrah Sfaira" },
  { label: "Mrah Sraje", value: "Mrah Sraje" },
  { label: "Mreijat", value: "Mreijat" },
  { label: "Mreijeh", value: "Mreijeh" },
  { label: "Mrouj", value: "Mrouj" },
  { label: "Mtaileb", value: "Mtaileb" },
  { label: "Mtein", value: "Mtein" },
  { label: "Mtolleh", value: "Mtolleh" },
  { label: "Nabatyeh", value: "Nabatyeh" },
  { label: "Nabay", value: "Nabay" },
  { label: "Nabha Damdoum", value: "Nabha Damdoum" },
  { label: "Nabha Harfouche", value: "Nabha Harfouche" },
  { label: "Nabha Kleili", value: "Nabha Kleili" },
  { label: "Nabha Mahfara", value: "Nabha Mahfara" },
  { label: "Nabi Aylla", value: "Nabi Aylla" },
  { label: "Nabi Chiit", value: "Nabi Chiit" },
  { label: "Nabi Inaam", value: "Nabi Inaam" },
  { label: "Nabi Osman", value: "Nabi Osman" },
  { label: "Nabi Rachadeh", value: "Nabi Rachadeh" },
  { label: "Nabi Sbat", value: "Nabi Sbat" },
  { label: "Nabi Youchaah", value: "Nabi Youchaah" },
  { label: "Nabi Youchah", value: "Nabi Youchah" },
  { label: "Naccache", value: "Naccache" },
  { label: "Nahleh", value: "Nahleh" },
  { label: "Nahmeh", value: "Nahmeh" },
  { label: "Nahr Ibrahim", value: "Nahr Ibrahim" },
  { label: "Nahriyeh", value: "Nahriyeh" },
  { label: "Nakhleh", value: "Nakhleh" },
  { label: "Nakra", value: "Nakra" },
  { label: "Namrine", value: "Namrine" },
  { label: "Nassiriyeh", value: "Nassiriyeh" },
  { label: "Nayra", value: "Nayra" },
  { label: "Nejjariyeh", value: "Nejjariyeh" },
  { label: "Nemayreh", value: "Nemayreh" },
  { label: "Nfeisseh", value: "Nfeisseh" },
  { label: "Niha", value: "Niha" },
  { label: "Niha", value: "Niha" },
  { label: "Nimrine", value: "Nimrine" },
  { label: "Nmeiriyeh", value: "Nmeiriyeh" },
  { label: "Noura", value: "Noura" },
  { label: "Nye Rachadeh", value: "Nye Rachadeh" },
  { label: "Obeidad", value: "Obeidad" },
  { label: "Oueinate", value: "Oueinate" },
  { label: "Ouyoun", value: "Ouyoun" },
  { label: "Port of Beirut", value: "Port of Beirut" },
  { label: "Qaaqayiet el-Jisr", value: "Qaaqayiet el-Jisr" },
  { label: "Qalamoun", value: "Qalamoun" },
  { label: "Qana", value: "Qana" },
  { label: "Qattin", value: "Qattin" },
  { label: "Qnat", value: "Qnat" },
  { label: "Qobeih", value: "Qobeih" },
  { label: "Qsaibeh", value: "Qsaibeh" },
  { label: "Qsaïbeh", value: "Qsaïbeh" },
  { label: "Quorayeh", value: "Quorayeh" }, 
  { label: "Raachine", value: "Raachine" },
  { label: "Racha", value: "Racha" },
  { label: "Rachana", value: "Rachana" },
  { label: "Rachaya", value: "Rachaya" },
  { label: "Rachaya el-Foukhar", value: "Rachaya el-Foukhar" },
  { label: "Rachdebbine", value: "Rachdebbine" },
  { label: "Rachedbine", value: "Rachedbine" },
  { label: "Rachiine", value: "Rachiine" },
  { label: "Rachkananey", value: "Rachkananey" },
  { label: "Rachkida", value: "Rachkida" },
  { label: "Racyay", value: "Racyay" },
  { label: "Rafid", value: "Rafid" },
  { label: "Rafid", value: "Rafid" },
  { label: "Rahbeh", value: "Rahbeh" },
  { label: "Rahit", value: "Rahit" },
  { label: "Ram", value: "Ram" },
  { label: "Ram", value: "Ram" },
  { label: "Ramassa", value: "Ramassa" },
  { label: "Rammah", value: "Rammah" },
  { label: "Ramout", value: "Ramout" },
  { label: "Ras Baalbeck", value: "Ras Baalbeck" },
  { label: "Ras el-Ain", value: "Ras el-Ain" },
  { label: "Ras el-Harf", value: "Ras el-Harf" },
  { label: "Ras el-Metn", value: "Ras el-Metn" },
  { label: "Ras Nhache", value: "Ras Nhache" },
  { label: "Ras Osta", value: "Ras Osta" },
  { label: "Ras Senhache", value: "Ras Senhache" },
  { label: "Ras-Beyrouth", value: "Ras-Beyrouth" },
  { label: "Raskifa", value: "Raskifa" },
  { label: "Ras-Meska", value: "Ras-Meska" },
  { label: "Rassiyeh", value: "Rassiyeh" },
  { label: "Rawda", value: "Rawda" },
  { label: "Rawda", value: "Rawda" },
  { label: "Rayak", value: "Rayak" },
  { label: "Rechmaya", value: "Rechmaya" },
  { label: "Remhala", value: "Remhala" },
  { label: "Reyfoun", value: "Reyfoun" },
  { label: "Rich", value: "Rich" },
  { label: "Riha", value: "Riha" },
  { label: "Rihanieh", value: "Rihanieh" },
  { label: "Rihaniyeh", value: "Rihaniyeh" },
  { label: "Rmadiyeh", value: "Rmadiyeh" },
  { label: "Rmeil", value: "Rmeil" },
  { label: "Rmeileh", value: "Rmeileh" },
  { label: "Rmeyleh", value: "Rmeyleh" },
  { label: "Rouayset el-Ballout", value: "Rouayset el-Ballout" },
  { label: "Roueisset el-Nehman", value: "Roueisset el-Nehman" },
  { label: "Roumieh", value: "Roumieh" },
  { label: "Roumine", value: "Roumine" },
  { label: "Roummaneh", value: "Roummaneh" }, 
  { label: "Saadine", value: "Saadine" },
  { label: "Saadnayel", value: "Saadnayel" },
  { label: "Sabbouba", value: "Sabbouba" },
  { label: "Sad el-Baouchrieh", value: "Sad el-Baouchrieh" },
  { label: "Sadikine", value: "Sadikine" },
  { label: "Sadiyeh", value: "Sadiyeh" },
  { label: "Safad el-Batikh", value: "Safad el-Batikh" },
  { label: "Safinet el-Dreib", value: "Safinet el-Dreib" },
  { label: "Safra", value: "Safra" },
  { label: "Safra", value: "Safra" },
  { label: "Saghbine", value: "Saghbine" },
  { label: "Sahel Alma", value: "Sahel Alma" },
  { label: "Sahlat Ma'a", value: "Sahlat Ma'a" },
  { label: "Saida", value: "Saida" },
  { label: "Saifi", value: "Saifi" },
  { label: "Saki Rechmaya", value: "Saki Rechmaya" },
  { label: "Sakiet el-Misk", value: "Sakiet el-Misk" },
  { label: "Saksakiyeh", value: "Saksakiyeh" },
  { label: "Sal'a", value: "Sal'a" },
  { label: "Salhiyeh", value: "Salhiyeh" },
  { label: "Salhiyeh", value: "Salhiyeh" },
  { label: "Salib", value: "Salib" },
  { label: "Sarafand", value: "Sarafand" },
  { label: "Sarafande", value: "Sarafande" },
  { label: "Sarba", value: "Sarba" },
  { label: "Sarba", value: "Sarba" },
  { label: "Sarba", value: "Sarba" },
  { label: "Sarhine", value: "Sarhine" },
  { label: "Sayaniyeh", value: "Sayaniyeh" },
  { label: "Saydeh", value: "Saydeh" },
  { label: "Sayssouq", value: "Sayssouq" },
  { label: "Sebhel", value: "Sebhel" },
  { label: "Sebline", value: "Sebline" },
  { label: "Sebnay", value: "Sebnay" },
  { label: "Sefri", value: "Sefri" },
  { label: "Sehayleh", value: "Sehayleh" },
  { label: "Sehleh", value: "Sehleh" },
  { label: "Seissouk", value: "Seissouk" },
  { label: "Selaata", value: "Selaata" },
  { label: "Selaata", value: "Selaata" },
  { label: "Semakiyeh", value: "Semakiyeh" },
  { label: "Semkaniyeh", value: "Semkaniyeh" },
  { label: "Serhel", value: "Serhel" },
  { label: "Sfaira", value: "Sfaira" },
  { label: "Sfeili", value: "Sfeili" },
  { label: "Sfeinet Katih", value: "Sfeinet Katih" },
  { label: "Sghar", value: "Sghar" },
  { label: "Sin el-Fil", value: "Sin el-Fil" },
  { label: "Sinay", value: "Sinay" },
  { label: "Sindiyaneh", value: "Sindiyaneh" },
  { label: "Sir el-Gharibeh", value: "Sir el-Gharibeh" },
  { label: "Sir Denniyeh", value: "Sir Denniyeh" },
  { label: "Smaeyeh", value: "Smaeyeh" },
  { label: "Smar Jbeil", value: "Smar Jbeil" },
  { label: "Sofar", value: "Sofar" },
  { label: "Sohmor", value: "Sohmor" },
  { label: "Soleh", value: "Soleh" },
  { label: "Souayra", value: "Souayra" },
  { label: "Soueisseh", value: "Soueisseh" },
  { label: "Soueisseh", value: "Soueisseh" },
  { label: "Souk el-Gharb", value: "Souk el-Gharb" },
  { label: "Sour", value: "Sour" },
  { label: "Souret", value: "Souret" },
  { label: "Souwaika", value: "Souwaika" },
  { label: "Souwaneh", value: "Souwaneh" },
  { label: "Srar", value: "Srar" },
  { label: "Srifa", value: "Srifa" },
  { label: "Sultan Yaacoub", value: "Sultan Yaacoub" },
  { label: "Sultanieh", value: "Sultanieh" }, 
  { label: "Ta'aboura", value: "Ta'aboura" },
  { label: "Taalabaya", value: "Taalabaya" },
  { label: "Taanayel", value: "Taanayel" },
  { label: "Tabarja", value: "Tabarja" },
  { label: "Tabbaneh", value: "Tabbaneh" },
  { label: "Tabbaya", value: "Tabbaya" },
  { label: "Tacheh", value: "Tacheh" },
  { label: "Tahweitat", value: "Tahweitat" },
  { label: "Tal Abbas", value: "Tal Abbas" },
  { label: "Tal el-Akhdar", value: "Tal el-Akhdar" },
  { label: "Tal Bibeh", value: "Tal Bibeh" },
  { label: "Tal Bireh", value: "Tal Bireh" },
  { label: "Tal Hemayra", value: "Tal Hemayra" },
  { label: "Tal Mehyan", value: "Tal Mehyan" },
  { label: "Tal Mohammad", value: "Tal Mohammad" },
  { label: "Tal Zanoub", value: "Tal Zanoub" },
  { label: "Talleh", value: "Talleh" },
  { label: "Talya", value: "Talya" },
  { label: "Tanbourite", value: "Tanbourite" },
  { label: "Tannoura", value: "Tannoura" },
  { label: "Tannourine", value: "Tannourine" },
  { label: "Tarane", value: "Tarane" },
  { label: "Taraya", value: "Taraya" },
  { label: "Tarchich", value: "Tarchich" },
  { label: "Tartej", value: "Tartej" },
  { label: "Tayer Flisseh", value: "Tayer Flisseh" },
  { label: "Tayr Debba", value: "Tayr Debba" },
  { label: "Tebnine", value: "Tebnine" },
  { label: "Teffahta", value: "Teffahta" },
  { label: "Teffahta", value: "Teffahta" },
  { label: "Tekrit", value: "Tekrit" },
  { label: "Tel Meyane", value: "Tel Meyane" },
  { label: "Temnine", value: "Temnine" },
  { label: "Terbol", value: "Terbol" },
  { label: "Terbol", value: "Terbol" },
  { label: "Tfayel", value: "Tfayel" },
  { label: "Thoum", value: "Thoum" },
  { label: "Tibeh", value: "Tibeh" },
  { label: "Tleil", value: "Tleil" },
  { label: "Tmenin", value: "Tmenin" },
  { label: "Torzaya", value: "Torzaya" },
  { label: "Toufikiyeh", value: "Toufikiyeh" },
  { label: "Toula", value: "Toula" },
  { label: "Toula Jebbeh", value: "Toula Jebbeh" },
  { label: "Touline", value: "Touline" },
  { label: "Toura", value: "Toura" },
  { label: "Tourza", value: "Tourza" },
  { label: "Touweiti", value: "Touweiti" },
  { label: "Tripoli", value: "Tripoli" }, 
  { label: "Wadi Arayech", value: "Wadi Arayech" },
  { label: "Wadi Asse", value: "Wadi Asse" },
  { label: "Wadi Baankoudine", value: "Wadi Baankoudine" },
  { label: "Wadi Bnehley", value: "Wadi Bnehley" },
  { label: "Wadi Bneit", value: "Wadi Bneit" },
  { label: "Wadi el-Delm", value: "Wadi el-Delm" },
  { label: "Wadi el-Zineh", value: "Wadi el-Zineh" },
  { label: "Wadi el-Hour", value: "Wadi el-Hour" },
  { label: "Wadi el-Laymoun", value: "Wadi el-Laymoun" },
  { label: "Wadi el-Set", value: "Wadi el-Set" },
  { label: "Wadi Fa'ara", value: "Wadi Fa'ara" },
  { label: "Wadi Jamous", value: "Wadi Jamous" },
  { label: "Wadi Karm", value: "Wadi Karm" },
  { label: "Wadi Mechmechi", value: "Wadi Mechmechi" },
  { label: "Wadi Nahleh", value: "Wadi Nahleh" },
  { label: "Wadi Rattal", value: "Wadi Rattal" },
  { label: "Wadi Safa Charki", value: "Wadi Safa Charki" },
  { label: "Wadi Turkman", value: "Wadi Turkman" },
  { label: "Wadi Zein", value: "Wadi Zein" },
  { label: "Wadih Khaled", value: "Wadih Khaled" },
  { label: "Wardanieh", value: "Wardanieh" },
  { label: "Wata el-Mrouj", value: "Wata el-Mrouj" },
  { label: "Wata Fares", value: "Wata Fares" },
  { label: "Wata Houb", value: "Wata Houb" },
  { label: "Watieh", value: "Watieh" },
  { label: "Y", value: "Y" },
  { label: "Yahchouche", value: "Yahchouche" },
  { label: "Yahfoufa", value: "Yahfoufa" },
  { label: "Yammouni", value: "Yammouni" },
  { label: "Yanta", value: "Yanta" },
  { label: "Yater", value: "Yater" },
  { label: "Ynouh", value: "Ynouh" },
  { label: "Yohmor", value: "Yohmor" },
  { label: "Youghon Oloke", value: "Youghon Oloke" },
  { label: "Younine", value: "Younine" },
  { label: "Younissiyeh", value: "Younissiyeh" }, 
  { label: "Zaarourieh", value: "Zaarourieh" },
  { label: "Zabkine", value: "Zabkine" },
  { label: "Zaboud", value: "Zaboud" },
  { label: "Zabougha", value: "Zabougha" },
  { label: "Zaghr Tighrine", value: "Zaghr Tighrine" },
  { label: "Zaghrin", value: "Zaghrin" },
  { label: "Zahleh", value: "Zahleh" },
  { label: "Zahrieh", value: "Zahrieh" },
  { label: "Zakrouk", value: "Zakrouk" },
  { label: "Zakroun", value: "Zakroun" },
  { label: "Zakzouk", value: "Zakzouk" },
  { label: "Zalka", value: "Zalka" },
  { label: "Zane", value: "Zane" },
  { label: "Zaoutar", value: "Zaoutar" },
  { label: "Zarazir", value: "Zarazir" },
  { label: "Zarhoun", value: "Zarhoun" },
  { label: "Zawarib", value: "Zawarib" },
  { label: "Zebdine", value: "Zebdine" },
  { label: "Zefta", value: "Zefta" },
  { label: "Zeghdraya", value: "Zeghdraya" },
  { label: "Zeghrine", value: "Zeghrine" },
  { label: "Zekrit", value: "Zekrit" },
  { label: "Zen", value: "Zen" },
  { label: "Zgharta", value: "Zgharta" },
  { label: "Zitta", value: "Zitta" },
  { label: "Zlaya", value: "Zlaya" },
  { label: "Zokak el-Blat", value: "Zokak el-Blat" },
  { label: "Zoueitini", value: "Zoueitini" },
  { label: "Zouk", value: "Zouk" },
  { label: "Zouk el-Kharab", value: "Zouk el-Kharab" },
  { label: "Zouk el-Hossayni", value: "Zouk el-Hossayni" },
  { label: "Zouk Hadareh", value: "Zouk Hadareh" },
  { label: "Zouk Hassineh", value: "Zouk Hassineh" },
  { label: "Zouk Hbalseh", value: "Zouk Hbalseh" },
  { label: "Zouk Kharab", value: "Zouk Kharab" },
  { label: "Zouk Mekacharine", value: "Zouk Mekacharine" },
  { label: "Zouk Mikaël", value: "Zouk Mikaël" },
  { label: "Zouk Mosbeh", value: "Zouk Mosbeh" },
  { label: "Zrariyeh", value: "Zrariyeh" },
  { label: "Zrariyeh", value: "Zrariyeh" },
];

// remove doublecated
const uniqueArray = c.filter((value, index) => {
  const _value = JSON.stringify(value);
  return (
    index ===
    c.findIndex((obj) => {
      return JSON.stringify(obj) === _value;
    })
  );
});

export default uniqueArray;
